[workspace]
members = [
    "exercises/0-intro",
    "exercises/A1/1-basic-syntax",
    "exercises/A1/2-move-semantics/",
    "exercises/B/1-my-serde-app",
    "exercises/B/3-fizzbuzz",
    "slides/examples/B-application-programming",
]
